server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  application:
    name: "cards"
  config:
    import: "configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  sql:
    init:
      mode: always
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: "cards"
    description: "learn API for cards"
    version: "1.1.0"
logging:
  level:
    com:
      learn:
        cards: DEBUG
resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 5
resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration:
        seconds: 5
      exponential-backoff-multiplier: 2
      enable-exponential-backoff: true

