server:
  port: 9000

spring:
  application:
    name: cards

  # ---- DataSource / JPA ----
  datasource:
    url: jdbc:h2:mem:cardsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  # ---- Config Server ----
  config:
    import: "configserver:http://configserver-ms:8071/"

  # ---- RabbitMQ ----
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
  cloud:
    kubernetes:
      discovery:
        discovery-server-url: https://kubernetes.default.svc
        all-namespaces: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true


info:
  app:
    name: "cards"
    description: "learn API for cards"
    version: "1.1.0"
#optional
logging:
  level:
    com:
      learn:
        cards: DEBUG

