spring:
  config:
    activate:
      on-profile: "qa"


build:
  version: "2.0"

loans:
  message: "Welcome to Bank loans related local APIs QA "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@bank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932