spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0"

loans:
  message: "Welcome to Bank loans related local APIs production"
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@bank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932