spring:
  application:
    name: gatewayserver
  config:
    import: "configserver:http://configserver-ms:8071/"
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 3s
  data:
    redis:
      connect-timeout: 2s
      host: redis
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "Microservices gateway"
    version: "1.0.0"

#optional
logging:
  level:
    com:
      learn:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 5
