{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.activeProfile }}
  SPRING_CONFIG_IMPORT: {{ .Values.global.configServerURL }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.global.eurekaServerURL }}
  SPRING_RABBITMQ_HOST: {{ .Values.global.rabbitmqHost }}
  SPRING_RABBITMQ_PORT: "{{ .Values.global.rabbitmqPort }}"
  SPRING_RABBITMQ_USERNAME: {{ .Values.global.rabbitmqUsername }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.global.rabbitmqPassword }}
{{- end -}}
