server:
  port: 8090

spring:
  application:
    name: loans
  # ---- DataSource / JPA ----
  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  # ---- Config Server ----
  config:
    import: "configserver:http://configserver-ms:8071/"

  # ---- RabbitMQ ----
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

  profiles:
    active: "prod"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver-ms:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: "loans"
    description: "learn API for loans"
    version: "1.1.0"
#optional
logging:
  level:
    com:
      learn:
        loans: DEBUG
