spring:
  application:
    name: eurekaserver
  config:
    import: "configserver:http://configserver-ms:8071/"
  rabbitmq:
    host: rabbit
    port: 5672
    username: "guest"
    password: "guest"
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true




