server:
  port: 8080

spring:
  application:
    name: accounts
  profiles:
    active: prod

  # ---- DataSource / JPA ----
  datasource:
    url: jdbc:h2:mem:accountsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  # ---- Config Server ----
  config:
    import: "configserver:http://configserver-ms:8071/"

  # ---- RabbitMQ ----
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver-ms:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: "accounts"
    description: "learn API for accounts"
    version: "1.1.0"

#optional
logging:
  level:
    com:
      learn:
        accounts: DEBUG