global:
  configMapName: eazybankdev-configmap
  activeProfile: default
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  rabbitmqHost: rabbitmq.default.svc.cluster.local
  rabbitmqPort: 5672
  rabbitmqUsername: guest
  rabbitmqPassword: guest
