server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/RANJEETJ06/ConfigSever.git"
          default-label: "master"
          timeout: 5
          clone-on-start: true
          searchPaths: src/main/resources/config
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: 'adj97FBR7OreKVDlOsZywVZ7YAPEI6vf'