apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: ranjeetjena06/configserver:v2
        ports:
        - containerPort: 8071
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: learn-configmap
              key: CONFIGSERVER_APPLICATION_NAME
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: learn-configmap
              key: SPRING_RABBITMQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: learn-configmap
              key: SPRING_RABBITMQ_PORT
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: learn-configmap
              key: SPRING_RABBITMQ_USERNAME
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: learn-configmap
              key: SPRING_RABBITMQ_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: configserver-ms
spec:
  selector:
    app: configserver
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
